### PR TITLE
add travis file

### PR DESCRIPTION
**Pull request by ghost**
- add travis-ci file
- use docker-compose latest version
- try to build via docker-compose (cannot use install.sh as it requires to provide magento credentials)

### CODE REVIEW

**Comment by aliuosio** [comment]
@x0rzkov Big Up Yourself.... THX

**Comment by aliuosio** [comment]
@x0rzkov 
The link to the travis build is not working...

**Comment by ghost** [comment]
you need to create an account to https://travis-ci.com/ and add your repository

after if you wanna pull the docker image to docker hub, you need also to create an account on https://hub.docker.com/

Then, I can improve the file for setting up your DOCKER_USERNAME and DOCKER_PASSWORD
https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

```bash
travis env --pro set DOCKER_USERNAME myusername
travis env --pro set DOCKER_PASSWORD secretsecret
```

**Comment by aliuosio** [comment]
cool leaning something new. i have not worked with travis.
Thanks for the inspiration so far.
we have learned a lot together

**Comment by aliuosio** [comment]
> * try to build via docker-compose (cannot use install.sh as it requires to provide magento credentials)
@x0rzkov 
you always have to set the magento.com credentials.
On the console during installation or with an auth.json in the htdocs folder.
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

**Comment by ghost** [comment]
oh shit, can't you use a json file with the credentials and encrypt it https://docs.travis-ci.com/user/encrypting-files/

**Comment by aliuosio** [comment]
@x0rzkov 
i will look the travis stuff in the following days up.
But the credentials are all ways individual data.

**Comment by aliuosio** [comment]
@x0rzkov 
please to make a successful build using or fork of this repo then i will merge it. 
the build failed on travis.

**Comment by ghost** [comment]
I will have a look at that today

**Comment by ghost** [comment]
Is it possible to provide a /home/mage2/.composer/auth.json in order to override the form requesting for credentials ? it will solve the problem

**Pull request merged**
